# This is a basic workflow to help you get started with Actions

name: macOS CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - build
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.4.0

    - name: Make CAmod
      run: make all
    - name: Package CAmod
      run: |
        echo $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        ./packaging/package-all.sh prep-CA $GITHUB_WORKSPACE
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CombinedArms-prep-CA-macOS.zip
        path: CombinedArms-prep-CA-macOS.zip
